# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.box="Jmy/debian11-vmware"
    monitoring.vm.hostname = "monitoring.do1.exam"
    monitoring.vm.network "private_network", ip: "192.168.69.123"
    config.vm.synced_folder "files/", "/vagrant"
    monitoring.vm.provision "shell", path: "provisioning/add_hosts.sh"
    monitoring.vm.provision "shell", path: "provisioning/install-elastic-stack.sh"
  end

  config.vm.define "containers" do |containers|
    containers.vm.box="Jmy/debian11-vmware"
    containers.vm.hostname = "containers.do1.exam"
    containers.vm.network "private_network", ip: "192.168.69.122"
	  containers.vm.provision "shell", path: "provisioning/add_hosts.sh"
    containers.vm.provision "shell", path: "provisioning/docker_install.sh"
    containers.vm.provision "shell", path: "provisioning/setup_gitea.sh"
    containers.vm.provision "shell", path: "provisioning/install-metricbeat.sh"
    config.vm.synced_folder "files/", "/vagrant"
  end

  config.vm.define "pipelines" do |pipelines|
    pipelines.vm.box="Jmy/debian11-vmware"
    pipelines.vm.hostname = "pipelines.do1.exam"
    pipelines.vm.network "private_network", ip: "192.168.69.121"
    pipelines.vm.network "forwarded_port", guest: 8080, host: 8080
	  pipelines.vm.provision "shell", path: "provisioning/add_hosts.sh"
    pipelines.vm.provision "shell", path: "provisioning/install_jenkins.sh"
	  pipelines.vm.provision "shell", path: "provisioning/setup_jenkins.sh"
    pipelines.vm.provision "shell", path: "provisioning/install-metricbeat.sh"
    config.vm.synced_folder "files/", "/vagrant"
  end

end